version: "3.9"

services:

  knowledgehub:

    build: .

    container_name: knowledgehub-ai

    restart: unless-stopped

    ports:
      - "8501:8501"

    env_file:
      - .env

    volumes:
      - ./data:/app/data