version: "3.9"

services:

  knowledgehub-api:

    build: .

    container_name: knowledgehub-api

    restart: unless-stopped

    command: >
      uvicorn backend.api:app
      --host 0.0.0.0
      --port 8000

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      PYTHONPATH: /app/src

    volumes:
      - ./data:/app/data

  knowledgehub-ui:

    build: .

    container_name: knowledgehub-ui

    restart: unless-stopped

    command: >
      streamlit run src/app.py
      --server.address=0.0.0.0
      --server.port=8501

    ports:
      - "8501:8501"

    env_file:
      - .env

    environment:
      PYTHONPATH: /app/src

    depends_on:
      - knowledgehub-api

    volumes:
      - ./data:/app/data